config/routes.rb
Callnepal::Application.routes.draw do
  root :to => 'pages#home'
  get 'about' => 'pages#about'
  get 'how_it_works' => 'pages#how_it_works'
  get 'faq' => 'pages#faq'
  get 'sign_up' => 'pages#sign_up'
  get 'sign_in' => 'pages#sign_in'

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def how_it_works
  end

  def faq
  end

  def sign_up
  end

  def sign_in
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<small>
		Developed by <%= link_to "suyesh", "http://facebook.com/suyesh" %>
	</small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%= link_to "CallNepal.me", root_path, class: "brand" %>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
      	<ul class="nav">
	        <li><%= link_to "Home", root_path %></li>
			   <li><%= link_to "How It Works", how_it_works_path %></li>
         <li><%= link_to "FAQ", faq_path %></li>
		    </ul>
		    <ul class="nav pull-right">
          <li><%= link_to "Login", sign_in_path %></li>
          
		    </ul>
      </div>
 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Callnepal</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
		
		<div class="container">
			<% flash.each do |name, msg| %>
				<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
			<% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
		</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/faq.html.erb
<h1>Pages#faq</h1>
<p>Find me in app/views/pages/faq.html.erb</p>

app/views/pages/home.html.erb
	<div class="hero-unit">
		<h1>Welcome to CallNepal</h1>
		<p>
			A Unique and easiest way to call your <i class="icon-heart"></i> loved ones. You just sit back, relax while we find you best rates and best call quality!!
		</p>
		<p>
			<%= link_to "Sign Up Now!", sign_up_path, class: "btn btn-primary btn-large" %>
		</p>
	</div>

app/views/pages/how_it_works.html.erb
<h1>Pages#how_it_works</h1>
<p>Find me in app/views/pages/how_it_works.html.erb</p>

app/views/pages/sign_in.html.erb
<h1>Pages#sign_in</h1>
<p>Find me in app/views/pages/sign_in.html.erb</p>

app/views/pages/sign_up.html.erb
<h1>Pages#sign_up</h1>
<p>Find me in app/views/pages/sign_up.html.erb</p>